/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package admin;

import component.MessageBox;
import database.DataHandler;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import user.UserHome2;

/**
 *
 * @author xialj
 */
public class AdminHome extends javax.swing.JFrame {

    private String levelPage = "-1";
    private Color color1 = new Color(242, 242, 242);
    private Color color2 = new Color(255, 255, 255);
    private String userUid = "-1";
    private String roomRid = "-1";
    private String commentCid = "-1";
    private String adminAid = "-1";

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        slide.setAnimate(15);
        slide.init(login, manager);
        usernameHint.setText(" ");
        passwordHint.setText(" ");

        menuPanel.setBackground(color1);
        logoutMenu.setBackground(color1);

//        userTable.getTableHeader().setOpaque(false);
//        userTable.getTableHeader().setBackground(color2);
        userTable.setModel(tableModel1);
        roomTable.setModel(tableModel2);
        commentTable.setModel(tableModel3);
        adminTable.setModel(tableModel4);

        alldataTable.setModel(tableModel6);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slide = new component.PanelSlide();
        login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JPasswordField();
        loginBt = new component.RoundPanel();
        loginLabel = new javax.swing.JLabel();
        usernameHint = new javax.swing.JLabel();
        passwordHint = new javax.swing.JLabel();
        manager = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        userMenu = new javax.swing.JPanel();
        userMenuLabel = new javax.swing.JLabel();
        roomMenu = new javax.swing.JPanel();
        roomMenuLabel = new javax.swing.JLabel();
        commentMenu = new javax.swing.JPanel();
        commentMenuLabel = new javax.swing.JLabel();
        adminMenu = new javax.swing.JPanel();
        adminMenuLabel = new javax.swing.JLabel();
        saleMenu = new javax.swing.JPanel();
        saleMenuLabel = new javax.swing.JLabel();
        alldataMenu = new javax.swing.JPanel();
        alldataMenuLabel = new javax.swing.JLabel();
        logoutMenu = new javax.swing.JPanel();
        logoutMenuLabel = new javax.swing.JLabel();
        pages = new javax.swing.JPanel();
        userPage = new javax.swing.JPanel();
        userUsername = new javax.swing.JTextField();
        userPassword = new javax.swing.JTextField();
        userRoomnumber = new javax.swing.JTextField();
        userInsertBt = new component.RoundPanel();
        userInsertLabel = new javax.swing.JLabel();
        userUpdateBt = new component.RoundPanel();
        userUpdateLabel = new javax.swing.JLabel();
        userDeleteBt = new component.RoundPanel();
        userDeleteLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        roomPage = new javax.swing.JPanel();
        roomRoomnumber = new javax.swing.JTextField();
        roomRoomtype = new javax.swing.JTextField();
        roomAvailablility = new javax.swing.JTextField();
        roomInsertBt = new component.RoundPanel();
        roomInsertLabel = new javax.swing.JLabel();
        roomUpdateBt = new component.RoundPanel();
        roomUpdateLabel = new javax.swing.JLabel();
        roomDeleteBt = new component.RoundPanel();
        roomDeleteLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        roomTable = new javax.swing.JTable();
        commentPage = new javax.swing.JPanel();
        commentFinishBt = new component.RoundPanel();
        commentFinishLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        commentTable = new javax.swing.JTable();
        commentMessageLabel = new javax.swing.JLabel();
        adminPage = new javax.swing.JPanel();
        adminUsername = new javax.swing.JTextField();
        adminPassword = new javax.swing.JTextField();
        adminLevel = new javax.swing.JTextField();
        adminInsertBt = new component.RoundPanel();
        adminInsertLabel = new javax.swing.JLabel();
        adminUpdateBt = new component.RoundPanel();
        adminUpdateLabel = new javax.swing.JLabel();
        adminDeleteBt = new component.RoundPanel();
        adminDeleteLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        salePage = new javax.swing.JPanel();
        alldataPage = new javax.swing.JPanel();
        alldataQueryBt = new component.RoundPanel();
        alldataQueryLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alldataTable = new javax.swing.JTable();
        tableNameCBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel1.setText("Username");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel2.setText("Password");

        usernameLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameLabelFocusGained(evt);
            }
        });

        passwordLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordLabelFocusGained(evt);
            }
        });

        loginBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBtMouseReleased(evt);
            }
        });
        loginBt.setLayout(new java.awt.GridLayout(1, 0));

        loginLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("Login");
        loginBt.add(loginLabel);

        usernameHint.setBackground(new java.awt.Color(255, 51, 51));
        usernameHint.setForeground(new java.awt.Color(255, 51, 51));
        usernameHint.setText(" ");

        passwordHint.setBackground(new java.awt.Color(255, 51, 51));
        passwordHint.setForeground(new java.awt.Color(255, 51, 51));
        passwordHint.setText(" ");
        passwordHint.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordHintFocusGained(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(374, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginBt, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameHint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                    .addGroup(loginLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(passwordHint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))))
                .addGap(369, 369, 369))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameHint)
                .addGap(24, 24, 24)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordHint)
                .addGap(32, 32, 32)
                .addComponent(loginBt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        manager.setBackground(new java.awt.Color(204, 255, 255));

        userMenu.setBackground(new java.awt.Color(255, 255, 255));
        userMenu.setPreferredSize(new java.awt.Dimension(150, 50));
        userMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userMenuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userMenuMouseReleased(evt);
            }
        });
        userMenu.setLayout(new java.awt.GridLayout(1, 0));

        userMenuLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        userMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userMenuLabel.setText("User");
        userMenu.add(userMenuLabel);

        roomMenu.setBackground(new java.awt.Color(255, 255, 255));
        roomMenu.setPreferredSize(new java.awt.Dimension(150, 50));
        roomMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roomMenuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roomMenuMouseReleased(evt);
            }
        });
        roomMenu.setLayout(new java.awt.GridLayout(1, 0));

        roomMenuLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        roomMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomMenuLabel.setText("Room");
        roomMenu.add(roomMenuLabel);

        commentMenu.setBackground(new java.awt.Color(255, 255, 255));
        commentMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                commentMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                commentMenuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                commentMenuMouseReleased(evt);
            }
        });
        commentMenu.setLayout(new java.awt.GridLayout(1, 0));

        commentMenuLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        commentMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commentMenuLabel.setText("Comment");
        commentMenu.add(commentMenuLabel);

        adminMenu.setBackground(new java.awt.Color(255, 255, 255));
        adminMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminMenuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adminMenuMouseReleased(evt);
            }
        });
        adminMenu.setLayout(new java.awt.GridLayout(1, 0));

        adminMenuLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        adminMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminMenuLabel.setText("Admin");
        adminMenu.add(adminMenuLabel);

        saleMenu.setBackground(new java.awt.Color(255, 255, 255));
        saleMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleMenuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                saleMenuMouseReleased(evt);
            }
        });
        saleMenu.setLayout(new java.awt.GridLayout(1, 0));

        saleMenuLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        saleMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saleMenuLabel.setText("Sales");
        saleMenu.add(saleMenuLabel);

        alldataMenu.setBackground(new java.awt.Color(255, 255, 255));
        alldataMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alldataMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alldataMenuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                alldataMenuMouseReleased(evt);
            }
        });
        alldataMenu.setLayout(new java.awt.GridLayout(1, 0));

        alldataMenuLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        alldataMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alldataMenuLabel.setText("Data");
        alldataMenu.add(alldataMenuLabel);

        logoutMenu.setBackground(new java.awt.Color(255, 255, 255));
        logoutMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMenuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                logoutMenuMouseReleased(evt);
            }
        });
        logoutMenu.setLayout(new java.awt.GridLayout(1, 0));

        logoutMenuLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        logoutMenuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutMenuLabel.setText("Logout");
        logoutMenu.add(logoutMenuLabel);

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commentMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saleMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alldataMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roomMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commentMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saleMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alldataMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pages.setLayout(new java.awt.CardLayout());

        userPage.setBackground(new java.awt.Color(255, 255, 255));

        userInsertBt.setMinimumSize(new java.awt.Dimension(41, 19));
        userInsertBt.setPreferredSize(new java.awt.Dimension(41, 19));
        userInsertBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userInsertBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userInsertBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userInsertBtMouseReleased(evt);
            }
        });
        userInsertBt.setLayout(new java.awt.GridLayout());

        userInsertLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        userInsertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userInsertLabel.setText("Insert");
        userInsertLabel.setPreferredSize(new java.awt.Dimension(41, 19));
        userInsertBt.add(userInsertLabel);

        userUpdateBt.setPreferredSize(new java.awt.Dimension(41, 19));
        userUpdateBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userUpdateBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userUpdateBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userUpdateBtMouseReleased(evt);
            }
        });
        userUpdateBt.setLayout(new java.awt.GridLayout());

        userUpdateLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        userUpdateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userUpdateLabel.setText("Update");
        userUpdateLabel.setPreferredSize(new java.awt.Dimension(41, 19));
        userUpdateBt.add(userUpdateLabel);

        userDeleteBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userDeleteBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userDeleteBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userDeleteBtMouseReleased(evt);
            }
        });
        userDeleteBt.setLayout(new java.awt.GridLayout());

        userDeleteLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        userDeleteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userDeleteLabel.setText("Delete");
        userDeleteLabel.setPreferredSize(new java.awt.Dimension(41, 19));
        userDeleteBt.add(userDeleteLabel);

        userTable.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        userTable.setGridColor(new java.awt.Color(255, 255, 255));
        userTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                userTableMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(userTable);

        javax.swing.GroupLayout userPageLayout = new javax.swing.GroupLayout(userPage);
        userPage.setLayout(userPageLayout);
        userPageLayout.setHorizontalGroup(
            userPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(userPageLayout.createSequentialGroup()
                        .addComponent(userUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userRoomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userInsertBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userUpdateBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userDeleteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userPageLayout.setVerticalGroup(
            userPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPageLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(userPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userRoomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(userUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(userInsertBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userDeleteBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(userUpdateBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        pages.add(userPage, "card2");

        roomPage.setBackground(new java.awt.Color(255, 255, 255));

        roomInsertBt.setMinimumSize(new java.awt.Dimension(41, 19));
        roomInsertBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomInsertBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roomInsertBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roomInsertBtMouseReleased(evt);
            }
        });
        roomInsertBt.setLayout(new java.awt.GridLayout());

        roomInsertLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        roomInsertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomInsertLabel.setText("Insert");
        roomInsertLabel.setPreferredSize(new java.awt.Dimension(41, 19));
        roomInsertBt.add(roomInsertLabel);

        roomUpdateBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomUpdateBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roomUpdateBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roomUpdateBtMouseReleased(evt);
            }
        });
        roomUpdateBt.setLayout(new java.awt.GridLayout());

        roomUpdateLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        roomUpdateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomUpdateLabel.setText("Update");
        roomUpdateLabel.setPreferredSize(new java.awt.Dimension(41, 19));
        roomUpdateBt.add(roomUpdateLabel);

        roomDeleteBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                roomDeleteBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                roomDeleteBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                roomDeleteBtMouseReleased(evt);
            }
        });
        roomDeleteBt.setLayout(new java.awt.GridLayout());

        roomDeleteLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        roomDeleteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        roomDeleteLabel.setText("Delete");
        roomDeleteLabel.setPreferredSize(new java.awt.Dimension(41, 19));
        roomDeleteBt.add(roomDeleteLabel);

        roomTable.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        roomTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        roomTable.setGridColor(new java.awt.Color(255, 255, 255));
        roomTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                roomTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(roomTable);

        javax.swing.GroupLayout roomPageLayout = new javax.swing.GroupLayout(roomPage);
        roomPage.setLayout(roomPageLayout);
        roomPageLayout.setHorizontalGroup(
            roomPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roomPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(roomPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(roomPageLayout.createSequentialGroup()
                        .addComponent(roomRoomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomRoomtype, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roomAvailablility, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(roomInsertBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roomUpdateBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roomDeleteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roomPageLayout.setVerticalGroup(
            roomPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roomPageLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(roomPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roomPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(roomRoomtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(roomAvailablility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(roomRoomnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(roomPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(roomInsertBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(roomDeleteBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(roomUpdateBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        pages.add(roomPage, "card3");

        commentPage.setBackground(new java.awt.Color(255, 255, 255));

        commentFinishBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                commentFinishBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                commentFinishBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                commentFinishBtMouseReleased(evt);
            }
        });
        commentFinishBt.setLayout(new java.awt.GridLayout());

        commentFinishLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        commentFinishLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commentFinishLabel.setText("Finish");
        commentFinishLabel.setPreferredSize(new java.awt.Dimension(41, 19));
        commentFinishBt.add(commentFinishLabel);

        commentTable.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        commentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        commentTable.setGridColor(new java.awt.Color(255, 255, 255));
        commentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                commentTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(commentTable);

        javax.swing.GroupLayout commentPageLayout = new javax.swing.GroupLayout(commentPage);
        commentPage.setLayout(commentPageLayout);
        commentPageLayout.setHorizontalGroup(
            commentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(commentPageLayout.createSequentialGroup()
                .addGroup(commentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(commentPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(commentPageLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(commentMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(commentFinishBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        commentPageLayout.setVerticalGroup(
            commentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commentPageLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(commentPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(commentFinishBt, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(commentMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        pages.add(commentPage, "card4");

        adminPage.setBackground(new java.awt.Color(255, 255, 255));

        adminInsertBt.setMinimumSize(new java.awt.Dimension(41, 19));
        adminInsertBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminInsertBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminInsertBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adminInsertBtMouseReleased(evt);
            }
        });
        adminInsertBt.setLayout(new java.awt.GridLayout());

        adminInsertLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        adminInsertLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminInsertLabel.setText("Insert");
        adminInsertLabel.setPreferredSize(new java.awt.Dimension(41, 19));
        adminInsertBt.add(adminInsertLabel);

        adminUpdateBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminUpdateBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminUpdateBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adminUpdateBtMouseReleased(evt);
            }
        });
        adminUpdateBt.setLayout(new java.awt.GridLayout());

        adminUpdateLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        adminUpdateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminUpdateLabel.setText("Update");
        adminUpdateLabel.setPreferredSize(new java.awt.Dimension(41, 19));
        adminUpdateBt.add(adminUpdateLabel);

        adminDeleteBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminDeleteBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                adminDeleteBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                adminDeleteBtMouseReleased(evt);
            }
        });
        adminDeleteBt.setLayout(new java.awt.GridLayout());

        adminDeleteLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        adminDeleteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminDeleteLabel.setText("Delete");
        adminDeleteLabel.setPreferredSize(new java.awt.Dimension(41, 19));
        adminDeleteBt.add(adminDeleteLabel);

        adminTable.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        adminTable.setGridColor(new java.awt.Color(255, 255, 255));
        adminTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminTableMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(adminTable);

        javax.swing.GroupLayout adminPageLayout = new javax.swing.GroupLayout(adminPage);
        adminPage.setLayout(adminPageLayout);
        adminPageLayout.setHorizontalGroup(
            adminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(adminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(adminPageLayout.createSequentialGroup()
                        .addComponent(adminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(adminLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(adminInsertBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminUpdateBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adminDeleteBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminPageLayout.setVerticalGroup(
            adminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPageLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(adminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(adminPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(adminUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(adminInsertBt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adminDeleteBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(adminUpdateBt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        pages.add(adminPage, "card5");

        salePage.setBackground(new java.awt.Color(255, 255, 255));
        salePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pages.add(salePage, "card6");

        alldataPage.setBackground(new java.awt.Color(255, 255, 255));

        alldataQueryBt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                alldataQueryBtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                alldataQueryBtMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                alldataQueryBtMouseReleased(evt);
            }
        });
        alldataQueryBt.setLayout(new java.awt.GridLayout());

        alldataQueryLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        alldataQueryLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alldataQueryLabel.setText("Query");
        alldataQueryBt.add(alldataQueryLabel);

        alldataTable.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        alldataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(alldataTable);

        tableNameCBox.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        tableNameCBox.setModel(new javax.swing.DefaultComboBoxModel(DataHandler.getTables()));

        javax.swing.GroupLayout alldataPageLayout = new javax.swing.GroupLayout(alldataPage);
        alldataPage.setLayout(alldataPageLayout);
        alldataPageLayout.setHorizontalGroup(
            alldataPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alldataPageLayout.createSequentialGroup()
                .addContainerGap(591, Short.MAX_VALUE)
                .addComponent(tableNameCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(alldataQueryBt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        alldataPageLayout.setVerticalGroup(
            alldataPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alldataPageLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(alldataPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alldataQueryBt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tableNameCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        pages.add(alldataPage, "card7");

        javax.swing.GroupLayout managerLayout = new javax.swing.GroupLayout(manager);
        manager.setLayout(managerLayout);
        managerLayout.setHorizontalGroup(
            managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pages, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );
        managerLayout.setVerticalGroup(
            managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(managerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pages, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout slideLayout = new javax.swing.GroupLayout(slide);
        slide.setLayout(slideLayout);
        slideLayout.setHorizontalGroup(
            slideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        slideLayout.setVerticalGroup(
            slideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(slide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtMouseReleased
        // TODO add your handling code here:
        String username = usernameLabel.getText();
        String password = passwordLabel.getText();
        boolean flag = true;
        if (username == null || username.trim().length() == 0) {
            usernameHint.setText("* Username cannot be empty");
            flag = false;
        }
        if (password == null || password.trim().length() == 0) {
            passwordHint.setText("* Password cannot be empty");
            flag = false;
        }

        if (flag) {

            String result = DataHandler.adminLogin(username, password);
            if (result.length() > 0) {
                usernameLabel.setText("");
                passwordLabel.setText("");
                levelPage = result;
                chcekLevel();
                setTabel(tableModel1, "user_info");
                slide.show(1);
            } else {
                passwordHint.setText("* Wrong username or password");
            }

        }

        //=======================
//        usernameLabel.setText("");
//        passwordLabel.setText("");
//        levelPage = "2";
//        chcekLevel();
//        setTabel(tableModel1, "user_info");
//        slide.show(1);
        //=======================
    }//GEN-LAST:event_loginBtMouseReleased

    private void loginBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtMouseEntered
        // TODO add your handling code here:
        loginLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 18));
    }//GEN-LAST:event_loginBtMouseEntered

    private void loginBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtMouseExited
        // TODO add your handling code here:
        loginLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_loginBtMouseExited

    private void usernameLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameLabelFocusGained
        // TODO add your handling code here:
        usernameHint.setText(" ");
    }//GEN-LAST:event_usernameLabelFocusGained

    private void passwordHintFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordHintFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_passwordHintFocusGained

    private void passwordLabelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLabelFocusGained
        // TODO add your handling code here:
        passwordHint.setText(" ");
    }//GEN-LAST:event_passwordLabelFocusGained

    private void userMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMenuMouseReleased
        // TODO add your handling code here:
        setMenuBackground(userMenu, roomMenu, commentMenu, adminMenu, saleMenu, alldataMenu, color2, color1);
        jumpPages(userPage, roomPage, commentPage, adminPage, salePage, alldataPage);

        setTabel(tableModel1, "user_info");

    }//GEN-LAST:event_userMenuMouseReleased

    private void roomMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomMenuMouseReleased
        // TODO add your handling code here:
        setMenuBackground(roomMenu, userMenu, commentMenu, adminMenu, saleMenu, alldataMenu, color2, color1);
        jumpPages(roomPage, userPage, commentPage, adminPage, salePage, alldataPage);
        setTabel(tableModel2, "room");
    }//GEN-LAST:event_roomMenuMouseReleased

    private void commentMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMenuMouseReleased
        // TODO add your handling code here:
        setMenuBackground(commentMenu, roomMenu, userMenu, adminMenu, saleMenu, alldataMenu, color2, color1);
        jumpPages(commentPage, roomPage, userPage, adminPage, salePage, alldataPage);
        setTabel(tableModel3, "comment");
    }//GEN-LAST:event_commentMenuMouseReleased

    private void adminMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMenuMouseReleased
        // TODO add your handling code here:
        setMenuBackground(adminMenu, commentMenu, roomMenu, userMenu, saleMenu, alldataMenu, color2, color1);
        jumpPages(adminPage, commentPage, roomPage, userPage, salePage, alldataPage);
        setTabel(tableModel4, "admin");
    }//GEN-LAST:event_adminMenuMouseReleased

    private void saleMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMenuMouseReleased
        // TODO add your handling code here:
        drawBarChart();
        setMenuBackground(saleMenu, adminMenu, commentMenu, roomMenu, userMenu, alldataMenu, color2, color1);
        jumpPages(salePage, adminPage, commentPage, roomPage, userPage, alldataPage);

    }//GEN-LAST:event_saleMenuMouseReleased

    private void alldataMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alldataMenuMouseReleased
        // TODO add your handling code here:
        setMenuBackground(alldataMenu, saleMenu, adminMenu, commentMenu, roomMenu, userMenu, color2, color1);
        jumpPages(alldataPage, salePage, adminPage, commentPage, roomPage, userPage);
        //tableModel6.setDataVector(DataHandler.getRows("user_info"), DataHandler.getTitles("user_info"));
        setTabel(tableModel6, "user_info");
    }//GEN-LAST:event_alldataMenuMouseReleased

    private void userMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMenuMouseEntered
        // TODO add your handling code here:
        userMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 18));
    }//GEN-LAST:event_userMenuMouseEntered

    private void userMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userMenuMouseExited
        // TODO add your handling code here:
        userMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_userMenuMouseExited

    private void roomMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomMenuMouseEntered
        // TODO add your handling code here:
        roomMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 18));
    }//GEN-LAST:event_roomMenuMouseEntered

    private void roomMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomMenuMouseExited
        // TODO add your handling code here:
        roomMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_roomMenuMouseExited

    private void commentMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMenuMouseEntered
        // TODO add your handling code here:
        commentMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 18));
    }//GEN-LAST:event_commentMenuMouseEntered

    private void commentMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentMenuMouseExited
        // TODO add your handling code here:
        commentMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_commentMenuMouseExited

    private void adminMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMenuMouseEntered
        // TODO add your handling code here:
        adminMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 18));
    }//GEN-LAST:event_adminMenuMouseEntered

    private void adminMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMenuMouseExited
        // TODO add your handling code here:
        adminMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_adminMenuMouseExited

    private void saleMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMenuMouseEntered
        // TODO add your handling code here:
        saleMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 18));
    }//GEN-LAST:event_saleMenuMouseEntered

    private void saleMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleMenuMouseExited
        // TODO add your handling code here:
        saleMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_saleMenuMouseExited

    private void alldataMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alldataMenuMouseEntered
        // TODO add your handling code here:
        alldataMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 18));
    }//GEN-LAST:event_alldataMenuMouseEntered

    private void alldataMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alldataMenuMouseExited
        // TODO add your handling code here:
        alldataMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_alldataMenuMouseExited

    private void logoutMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMenuMouseEntered
        // TODO add your handling code here:
        logoutMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 18));
    }//GEN-LAST:event_logoutMenuMouseEntered

    private void logoutMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMenuMouseExited
        // TODO add your handling code here:
        logoutMenuLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_logoutMenuMouseExited

    private void logoutMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMenuMouseReleased
        // TODO add your handling code here:
        levelPage = "-1";
        slide.show(0);
    }//GEN-LAST:event_logoutMenuMouseReleased

    private void alldataQueryBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alldataQueryBtMouseReleased
        // TODO add your handling code here:
        String tName = tableNameCBox.getSelectedItem().toString();
        tableModel6.setDataVector(DataHandler.getRows(tName), DataHandler.getTitles(tName));
    }//GEN-LAST:event_alldataQueryBtMouseReleased

    private void alldataQueryBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alldataQueryBtMouseEntered
        // TODO add your handling code here:
        alldataQueryLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_alldataQueryBtMouseEntered

    private void alldataQueryBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alldataQueryBtMouseExited
        // TODO add your handling code here:
        alldataQueryLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 14));
    }//GEN-LAST:event_alldataQueryBtMouseExited

    private void userTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseClicked
        // TODO add your handling code here:
        int row = userTable.getSelectedRow();
        userUid = userTable.getModel().getValueAt(row, 0).toString();
        userUsername.setText(userTable.getModel().getValueAt(row, 1).toString());
        userPassword.setText(userTable.getModel().getValueAt(row, 2).toString());
        if (userTable.getModel().getValueAt(row, 3) != null) {
            userRoomnumber.setText(userTable.getModel().getValueAt(row, 3).toString());
        }

    }//GEN-LAST:event_userTableMouseClicked

    private void roomTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomTableMouseClicked
        // TODO add your handling code here:
        int row = roomTable.getSelectedRow();
        roomRid = roomTable.getModel().getValueAt(row, 0).toString();
        roomRoomnumber.setText(roomTable.getModel().getValueAt(row, 1).toString());
        roomRoomtype.setText(roomTable.getModel().getValueAt(row, 2).toString());
        if (roomTable.getModel().getValueAt(row, 3) != null) {
            roomAvailablility.setText(roomTable.getModel().getValueAt(row, 3).toString());
        }

    }//GEN-LAST:event_roomTableMouseClicked

    private void userTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTableMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_userTableMouseReleased

    private void adminTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminTableMouseClicked
        // TODO add your handling code here:
        int row = adminTable.getSelectedRow();
        adminAid = adminTable.getModel().getValueAt(row, 0).toString();
        adminUsername.setText(adminTable.getModel().getValueAt(row, 1).toString());
        adminPassword.setText(adminTable.getModel().getValueAt(row, 2).toString());
        if (adminTable.getModel().getValueAt(row, 3) != null) {
            adminLevel.setText(adminTable.getModel().getValueAt(row, 3).toString());
        }
    }//GEN-LAST:event_adminTableMouseClicked

    private void userInsertBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userInsertBtMouseReleased
        // TODO add your handling code here:
        String username = userUsername.getText();
        String password = userPassword.getText();
        String roomnumber = userRoomnumber.getText();
        if (username != null && username.trim().length() != 0 && password != null && password.trim().length() != 0 && roomnumber != null && roomnumber.trim().length() != 0) {
            DataHandler.insertUser(username, password, roomnumber);
            setTabel(tableModel1, "user_info");
            setTextFile(userUsername, userPassword, userRoomnumber);
        } else {
            showMessage("Please fill out the form.");
        }

    }//GEN-LAST:event_userInsertBtMouseReleased

    private void userUpdateBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userUpdateBtMouseReleased
        // TODO add your handling code here:

        String username = userUsername.getText();
        String password = userPassword.getText();
        String roomnumber = userRoomnumber.getText();
        if (username != null && username.trim().length() != 0 && password != null && password.trim().length() != 0 && roomnumber != null && roomnumber.trim().length() != 0) {
            DataHandler.updateUsser(userUid, username, password, roomnumber);
            setTabel(tableModel1, "user_info");
            setTextFile(userUsername, userPassword, userRoomnumber);
        } else {
            showMessage("Please fill out the form.");
        }
    }//GEN-LAST:event_userUpdateBtMouseReleased

    private void userDeleteBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDeleteBtMouseReleased
        // TODO add your handling code here:
        if (!"-1".equals(userUid)) {
            System.out.println("userUid+" + userUid);
            DataHandler.deleteUserById(userUid);
            setTabel(tableModel1, "user_info");
            setTextFile(userUsername, userPassword, userRoomnumber);
        }

    }//GEN-LAST:event_userDeleteBtMouseReleased

    private void roomInsertBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomInsertBtMouseReleased
        // TODO add your handling code here:
        String roomnumber = roomRoomnumber.getText();
        String type = roomRoomtype.getText();
        String availablility = roomAvailablility.getText();
        if (roomnumber != null && roomnumber.trim().length() != 0 && type != null && type.trim().length() != 0 && availablility != null && availablility.trim().length() != 0) {
            DataHandler.insertRoom(roomnumber, type, availablility);
            setTabel(tableModel2, "room");
            setTextFile(roomRoomnumber, roomRoomtype, roomAvailablility);
        } else {
            showMessage("Please fill out the form.");
        }
    }//GEN-LAST:event_roomInsertBtMouseReleased

    private void roomUpdateBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomUpdateBtMouseReleased
        // TODO add your handling code here:
        String roomnumber = roomRoomnumber.getText();
        String type = roomRoomtype.getText();
        String availablility = roomAvailablility.getText();

        if (roomnumber != null && roomnumber.trim().length() != 0 && type != null && type.trim().length() != 0 && availablility != null && availablility.trim().length() != 0) {
            DataHandler.updateRoom(roomRid, roomnumber, type, availablility);
            setTabel(tableModel2, "room");
            setTextFile(roomRoomnumber, roomRoomtype, roomAvailablility);
        } else {
            showMessage("Please fill out the form.");
        }
    }//GEN-LAST:event_roomUpdateBtMouseReleased

    private void roomDeleteBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomDeleteBtMouseReleased
        // TODO add your handling code here:
        if (!"-1".equals(roomRid)) {
            DataHandler.deleteRoomById(roomRid);
            setTabel(tableModel2, "room");
            setTextFile(roomRoomnumber, roomRoomtype, roomAvailablility);
        }
    }//GEN-LAST:event_roomDeleteBtMouseReleased

    private void adminInsertBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminInsertBtMouseReleased
        // TODO add your handling code here:
        String username = adminUsername.getText();
        String password = adminPassword.getText();
        String level = adminLevel.getText();
        if (username != null && username.trim().length() != 0 && password != null && password.trim().length() != 0 && level != null && level.trim().length() != 0) {
            DataHandler.insertAdmin(username, password, level);
            setTabel(tableModel4, "admin");
            setTextFile(adminUsername, adminPassword, adminLevel);
        } else {
            showMessage("Please fill out the form.");
        }
    }//GEN-LAST:event_adminInsertBtMouseReleased

    private void adminUpdateBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUpdateBtMouseReleased
        // TODO add your handling code here:
        String username = adminUsername.getText();
        String password = adminPassword.getText();
        String level = adminLevel.getText();
        if (username != null && username.trim().length() != 0 && password != null && password.trim().length() != 0 && level != null && level.trim().length() != 0) {
            DataHandler.updateAdmin(adminAid, username, password, level);
            setTabel(tableModel4, "admin");
            setTextFile(adminUsername, adminPassword, adminLevel);
        } else {
            showMessage("Please fill out the form.");
        }
    }//GEN-LAST:event_adminUpdateBtMouseReleased

    private void adminDeleteBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminDeleteBtMouseReleased
        // TODO add your handling code here:
        if (!"-1".equals(adminAid)) {
            DataHandler.deleteAdminById(adminAid);
            setTabel(tableModel4, "admin");
            setTextFile(adminUsername, adminPassword, adminLevel);
        }
    }//GEN-LAST:event_adminDeleteBtMouseReleased

    private void commentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentTableMouseClicked
        // TODO add your handling code here:
        int row = commentTable.getSelectedRow();
        commentCid = commentTable.getModel().getValueAt(row, 0).toString();

        commentMessageLabel.setText(commentTable.getModel().getValueAt(row, 2).toString());
    }//GEN-LAST:event_commentTableMouseClicked

    private void commentFinishBtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentFinishBtMouseReleased
        // TODO add your handling code here:

        if (!"-1".equals(commentCid)) {
            DataHandler.updateComment(commentCid);
            setTabel(tableModel3, "comment");

        }
    }//GEN-LAST:event_commentFinishBtMouseReleased

    private void userInsertBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userInsertBtMouseEntered
        // TODO add your handling code here:
        userInsertLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_userInsertBtMouseEntered

    private void userInsertBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userInsertBtMouseExited
        // TODO add your handling code here:
        userInsertLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 14));
    }//GEN-LAST:event_userInsertBtMouseExited

    private void userUpdateBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userUpdateBtMouseEntered
        // TODO add your handling code here:
        userUpdateLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_userUpdateBtMouseEntered

    private void userUpdateBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userUpdateBtMouseExited
        // TODO add your handling code here:
        userUpdateLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 14));
    }//GEN-LAST:event_userUpdateBtMouseExited

    private void userDeleteBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDeleteBtMouseEntered
        // TODO add your handling code here:
        userDeleteLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_userDeleteBtMouseEntered

    private void userDeleteBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDeleteBtMouseExited
        // TODO add your handling code here:
        userDeleteLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 14));
    }//GEN-LAST:event_userDeleteBtMouseExited

    private void roomInsertBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomInsertBtMouseEntered
        // TODO add your handling code here:
        roomInsertLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_roomInsertBtMouseEntered

    private void roomInsertBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomInsertBtMouseExited
        // TODO add your handling code here:
        roomInsertLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 14));
    }//GEN-LAST:event_roomInsertBtMouseExited

    private void roomUpdateBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomUpdateBtMouseEntered
        // TODO add your handling code here:
        roomUpdateLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_roomUpdateBtMouseEntered

    private void roomUpdateBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomUpdateBtMouseExited
        // TODO add your handling code here:
        roomUpdateLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 14));
    }//GEN-LAST:event_roomUpdateBtMouseExited

    private void roomDeleteBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomDeleteBtMouseEntered
        // TODO add your handling code here:
        roomDeleteLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_roomDeleteBtMouseEntered

    private void roomDeleteBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_roomDeleteBtMouseExited
        // TODO add your handling code here:
        roomDeleteLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 14));
    }//GEN-LAST:event_roomDeleteBtMouseExited

    private void commentFinishBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentFinishBtMouseEntered
        // TODO add your handling code here:
        commentFinishLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_commentFinishBtMouseEntered

    private void commentFinishBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_commentFinishBtMouseExited
        // TODO add your handling code here:
        commentFinishLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 14));
    }//GEN-LAST:event_commentFinishBtMouseExited

    private void adminInsertBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminInsertBtMouseEntered
        // TODO add your handling code here:
        adminInsertLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_adminInsertBtMouseEntered

    private void adminInsertBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminInsertBtMouseExited
        // TODO add your handling code here:
        adminInsertLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 14));
    }//GEN-LAST:event_adminInsertBtMouseExited

    private void adminUpdateBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUpdateBtMouseEntered
        // TODO add your handling code here:
        adminUpdateLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_adminUpdateBtMouseEntered

    private void adminUpdateBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUpdateBtMouseExited
        // TODO add your handling code here:
        adminUpdateLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 14));
    }//GEN-LAST:event_adminUpdateBtMouseExited

    private void adminDeleteBtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminDeleteBtMouseEntered
        // TODO add your handling code here:
        adminDeleteLabel.setFont(new Font("Microsoft YaHei UI", Font.BOLD, 14));
    }//GEN-LAST:event_adminDeleteBtMouseEntered

    private void adminDeleteBtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminDeleteBtMouseExited
        // TODO add your handling code here:
        adminDeleteLabel.setFont(new Font("Microsoft YaHei UI", Font.PLAIN, 14));
    }//GEN-LAST:event_adminDeleteBtMouseExited

    private void chcekLevel() {
        System.out.println("level:" + levelPage);
        if ("1".equals(levelPage)) {
            adminMenu.setVisible(false);
            saleMenu.setVisible(false);
            alldataMenu.setVisible(false);
        } else if ("2".equals(levelPage)) {
            adminMenu.setVisible(true);
            saleMenu.setVisible(true);
            alldataMenu.setVisible(true);
        }
        setMenuBackground(userMenu, roomMenu, commentMenu, adminMenu, saleMenu, alldataMenu, color2, color1);
        jumpPages(userPage, roomPage, commentPage, adminPage, salePage, alldataPage);

    }

    private void setMenuBackground(JPanel panel1, JPanel panel2, JPanel panel3, JPanel panel4, JPanel panel5, JPanel panel6, Color color1, Color color2) {
        panel1.setBackground(color1);
        panel2.setBackground(color2);
        panel3.setBackground(color2);
        panel4.setBackground(color2);
        panel5.setBackground(color2);
        panel6.setBackground(color2);

    }

    private void jumpPages(JPanel panel1, JPanel panel2, JPanel panel3, JPanel panel4, JPanel panel5, JPanel panel6) {
        panel1.setVisible(true);
        panel2.setVisible(false);
        panel3.setVisible(false);
        panel4.setVisible(false);
        panel5.setVisible(false);
        panel6.setVisible(false);
    }

    private void setTabel(DefaultTableModel tableModel, String name) {
        tableModel.setDataVector(DataHandler.getRows(name), DataHandler.getTitles(name));
    }

    // show messsage
    private void showMessage(String text) {
        MessageBox messageBox = new MessageBox(text);
        messageBox.setVisible(true);
        messageBox.setResizable(false);
        messageBox.setLocationRelativeTo(null);
    }

    // set textfile to empty
    private void setTextFile(JTextField t1, JTextField t2, JTextField t3) {
        t1.setText("");
        t2.setText("");
        t3.setText("");
    }

    private void drawBarChart() {
        // Create Dataset  
        CategoryDataset dataset = DataHandler.ueryGoodssDataset();//createDataset();

        //Create chart  
        JFreeChart chart = ChartFactory.createBarChart(
                "Goods Sales Volume Analysis", //Chart Title  
                "Goods", // Category axis  
                "Sales volume", // Value axis  
                dataset,
                PlotOrientation.VERTICAL,
                true, true, false
        );
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new java.awt.Dimension(750, 500));

        salePage.add(chartPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50));
        salePage.validate();

    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.RoundPanel adminDeleteBt;
    private javax.swing.JLabel adminDeleteLabel;
    private component.RoundPanel adminInsertBt;
    private javax.swing.JLabel adminInsertLabel;
    private javax.swing.JTextField adminLevel;
    private javax.swing.JPanel adminMenu;
    private javax.swing.JLabel adminMenuLabel;
    private javax.swing.JPanel adminPage;
    private javax.swing.JTextField adminPassword;
    private javax.swing.JTable adminTable;
    private component.RoundPanel adminUpdateBt;
    private javax.swing.JLabel adminUpdateLabel;
    private javax.swing.JTextField adminUsername;
    private javax.swing.JPanel alldataMenu;
    private javax.swing.JLabel alldataMenuLabel;
    private javax.swing.JPanel alldataPage;
    private component.RoundPanel alldataQueryBt;
    private javax.swing.JLabel alldataQueryLabel;
    private javax.swing.JTable alldataTable;
    private component.RoundPanel commentFinishBt;
    private javax.swing.JLabel commentFinishLabel;
    private javax.swing.JPanel commentMenu;
    private javax.swing.JLabel commentMenuLabel;
    private javax.swing.JLabel commentMessageLabel;
    private javax.swing.JPanel commentPage;
    private javax.swing.JTable commentTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel login;
    private component.RoundPanel loginBt;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPanel logoutMenu;
    private javax.swing.JLabel logoutMenuLabel;
    private javax.swing.JPanel manager;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel pages;
    private javax.swing.JLabel passwordHint;
    private javax.swing.JPasswordField passwordLabel;
    private javax.swing.JTextField roomAvailablility;
    private component.RoundPanel roomDeleteBt;
    private javax.swing.JLabel roomDeleteLabel;
    private component.RoundPanel roomInsertBt;
    private javax.swing.JLabel roomInsertLabel;
    private javax.swing.JPanel roomMenu;
    private javax.swing.JLabel roomMenuLabel;
    private javax.swing.JPanel roomPage;
    private javax.swing.JTextField roomRoomnumber;
    private javax.swing.JTextField roomRoomtype;
    private javax.swing.JTable roomTable;
    private component.RoundPanel roomUpdateBt;
    private javax.swing.JLabel roomUpdateLabel;
    private javax.swing.JPanel saleMenu;
    private javax.swing.JLabel saleMenuLabel;
    private javax.swing.JPanel salePage;
    private component.PanelSlide slide;
    private javax.swing.JComboBox<String> tableNameCBox;
    private component.RoundPanel userDeleteBt;
    private javax.swing.JLabel userDeleteLabel;
    private component.RoundPanel userInsertBt;
    private javax.swing.JLabel userInsertLabel;
    private javax.swing.JPanel userMenu;
    private javax.swing.JLabel userMenuLabel;
    private javax.swing.JPanel userPage;
    private javax.swing.JTextField userPassword;
    private javax.swing.JTextField userRoomnumber;
    private javax.swing.JTable userTable;
    private component.RoundPanel userUpdateBt;
    private javax.swing.JLabel userUpdateLabel;
    private javax.swing.JTextField userUsername;
    private javax.swing.JLabel usernameHint;
    private javax.swing.JTextField usernameLabel;
    // End of variables declaration//GEN-END:variables
    private javax.swing.table.DefaultTableModel tableModel1 = new javax.swing.table.DefaultTableModel();
    private javax.swing.table.DefaultTableModel tableModel2 = new javax.swing.table.DefaultTableModel();
    private javax.swing.table.DefaultTableModel tableModel3 = new javax.swing.table.DefaultTableModel();
    private javax.swing.table.DefaultTableModel tableModel4 = new javax.swing.table.DefaultTableModel();
    private javax.swing.table.DefaultTableModel tableModel5 = new javax.swing.table.DefaultTableModel();
    private javax.swing.table.DefaultTableModel tableModel6 = new javax.swing.table.DefaultTableModel();
}
