/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package user;

import database.DataHandler;
import java.awt.Color;

/**
 *
 * @author xialj
 */
public class userLogin extends javax.swing.JFrame {

    /**
     * Creates new form userLogin
     */
    public userLogin() {
        initComponents();
        slide.setAnimate(15);
        slide.init(loginPage, signupPage);

        usernameLoginHint.setText(" ");
        passwordLoginHint.setText(" ");
        usernameSignupHint.setText(" ");
        passwordSignupHint.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slide = new component.PanelSlide();
        loginPage = new javax.swing.JPanel();
        loginLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        usernameLogin = new javax.swing.JTextField();
        underline1 = new javax.swing.JLabel();
        usernameLoginHint = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        underline2 = new javax.swing.JLabel();
        passwordLogin = new javax.swing.JPasswordField();
        passwordLoginHint = new javax.swing.JLabel();
        loginBT = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        signupNowLabel = new javax.swing.JLabel();
        signupPage = new javax.swing.JPanel();
        userSignup = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        usernameSignup = new javax.swing.JTextField();
        underline3 = new javax.swing.JLabel();
        usernameSignupHint = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        underline4 = new javax.swing.JLabel();
        passwordSignup = new javax.swing.JPasswordField();
        passwordSignupHint = new javax.swing.JLabel();
        signupBT = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        backToLoginLabel = new javax.swing.JLabel();
        signupLogo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        slide.setPreferredSize(new java.awt.Dimension(500, 400));

        loginPage.setBackground(new java.awt.Color(0, 0, 0));
        loginPage.setPreferredSize(new java.awt.Dimension(500, 400));
        loginPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginLogo.setBackground(new java.awt.Color(253, 207, 102));
        loginLogo.setPreferredSize(new java.awt.Dimension(250, 400));
        loginLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        loginLogo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");
        loginLogo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        loginPage.add(loginLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        userLogin.setBackground(new java.awt.Color(0, 95, 89));
        userLogin.setPreferredSize(new java.awt.Dimension(250, 400));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username");

        usernameLogin.setBackground(new java.awt.Color(0, 95, 89));
        usernameLogin.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        usernameLogin.setForeground(new java.awt.Color(255, 255, 255));
        usernameLogin.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        usernameLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameLoginFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameLoginFocusLost(evt);
            }
        });

        underline1.setBackground(new java.awt.Color(255, 255, 255));
        underline1.setForeground(new java.awt.Color(255, 255, 255));
        underline1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        usernameLoginHint.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        usernameLoginHint.setForeground(new java.awt.Color(255, 51, 51));
        usernameLoginHint.setText(" ");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password");

        underline2.setBackground(new java.awt.Color(255, 255, 255));
        underline2.setForeground(new java.awt.Color(255, 255, 255));
        underline2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        passwordLogin.setBackground(new java.awt.Color(0, 95, 89));
        passwordLogin.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        passwordLogin.setForeground(new java.awt.Color(255, 255, 255));
        passwordLogin.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        passwordLogin.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordLoginFocusGained(evt);
            }
        });

        passwordLoginHint.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        passwordLoginHint.setForeground(new java.awt.Color(255, 51, 51));
        passwordLoginHint.setText(" ");

        loginBT.setBackground(new java.awt.Color(253, 207, 102));
        loginBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginBTMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                loginBTMouseReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Login");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel9MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout loginBTLayout = new javax.swing.GroupLayout(loginBT);
        loginBT.setLayout(loginBTLayout);
        loginBTLayout.setHorizontalGroup(
            loginBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBTLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel9)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        loginBTLayout.setVerticalGroup(
            loginBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginBTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        signupNowLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        signupNowLabel.setForeground(new java.awt.Color(255, 255, 255));
        signupNowLabel.setText("Sign up now");
        signupNowLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupNowLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupNowLabelMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signupNowLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout userLoginLayout = new javax.swing.GroupLayout(userLogin);
        userLogin.setLayout(userLoginLayout);
        userLoginLayout.setHorizontalGroup(
            userLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLoginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(userLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loginBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordLoginHint)
                    .addComponent(underline2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(usernameLoginHint)
                    .addComponent(underline1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(usernameLogin)
                    .addComponent(passwordLogin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLoginLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(signupNowLabel)
                .addGap(84, 84, 84))
        );
        userLoginLayout.setVerticalGroup(
            userLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLoginLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underline1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameLoginHint)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underline2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordLoginHint)
                .addGap(18, 18, 18)
                .addComponent(loginBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signupNowLabel)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        loginPage.add(userLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 0, 260, -1));

        signupPage.setBackground(new java.awt.Color(0, 0, 0));
        signupPage.setPreferredSize(new java.awt.Dimension(500, 400));
        signupPage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userSignup.setBackground(new java.awt.Color(0, 95, 89));
        userSignup.setPreferredSize(new java.awt.Dimension(250, 400));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Username");

        usernameSignup.setBackground(new java.awt.Color(0, 95, 89));
        usernameSignup.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        usernameSignup.setForeground(new java.awt.Color(255, 255, 255));
        usernameSignup.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        usernameSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernameSignupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameSignupFocusLost(evt);
            }
        });

        underline3.setBackground(new java.awt.Color(255, 255, 255));
        underline3.setForeground(new java.awt.Color(255, 255, 255));
        underline3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        usernameSignupHint.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        usernameSignupHint.setForeground(new java.awt.Color(255, 51, 51));
        usernameSignupHint.setText(" ");

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Password");

        underline4.setBackground(new java.awt.Color(255, 255, 255));
        underline4.setForeground(new java.awt.Color(255, 255, 255));
        underline4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        passwordSignup.setBackground(new java.awt.Color(0, 95, 89));
        passwordSignup.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        passwordSignup.setForeground(new java.awt.Color(255, 255, 255));
        passwordSignup.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        passwordSignup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordSignupFocusGained(evt);
            }
        });

        passwordSignupHint.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        passwordSignupHint.setForeground(new java.awt.Color(255, 51, 51));
        passwordSignupHint.setText(" ");

        signupBT.setBackground(new java.awt.Color(253, 207, 102));
        signupBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signupBTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signupBTMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                signupBTMouseReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sign up");

        javax.swing.GroupLayout signupBTLayout = new javax.swing.GroupLayout(signupBT);
        signupBT.setLayout(signupBTLayout);
        signupBTLayout.setHorizontalGroup(
            signupBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupBTLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel11)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        signupBTLayout.setVerticalGroup(
            signupBTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupBTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        backToLoginLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        backToLoginLabel.setForeground(new java.awt.Color(255, 255, 255));
        backToLoginLabel.setText("Back to Login");
        backToLoginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backToLoginLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backToLoginLabelMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                backToLoginLabelMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout userSignupLayout = new javax.swing.GroupLayout(userSignup);
        userSignup.setLayout(userSignupLayout);
        userSignupLayout.setHorizontalGroup(
            userSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSignupLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(userSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(signupBT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordSignupHint)
                    .addComponent(underline4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(usernameSignupHint)
                    .addComponent(underline3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addComponent(usernameSignup)
                    .addComponent(passwordSignup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userSignupLayout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(backToLoginLabel)
                .addGap(84, 84, 84))
        );
        userSignupLayout.setVerticalGroup(
            userSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userSignupLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underline3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameSignupHint)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(underline4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordSignupHint)
                .addGap(18, 18, 18)
                .addComponent(signupBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backToLoginLabel)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        signupPage.add(userSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, -1));

        signupLogo.setBackground(new java.awt.Color(253, 207, 102));
        signupLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user plus-fill.png"))); // NOI18N
        signupLogo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sign up");
        signupLogo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        signupPage.add(signupLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 240, 400));

        javax.swing.GroupLayout slideLayout = new javax.swing.GroupLayout(slide);
        slide.setLayout(slideLayout);
        slideLayout.setHorizontalGroup(
            slideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slideLayout.createSequentialGroup()
                .addComponent(loginPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(slideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slideLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signupPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        slideLayout.setVerticalGroup(
            slideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(slideLayout.createSequentialGroup()
                .addComponent(loginPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(slideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, slideLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signupPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(slide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(slide, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupNowLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupNowLabelMouseReleased
        // TODO add your handling code here:
        slide.show(1);
    }//GEN-LAST:event_signupNowLabelMouseReleased

    private void backToLoginLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginLabelMouseReleased
        // TODO add your handling code here:
        slide.show(0);
    }//GEN-LAST:event_backToLoginLabelMouseReleased

    private void jLabel9MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel9MouseReleased

    private void loginBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBTMouseReleased
        // TODO add your handling code here:
        String username = usernameLogin.getText();
        String password = passwordLogin.getText();
        boolean flag = true;
        if (username == null || username.trim().length() == 0) {
            usernameLoginHint.setText("* Username cannot be empty");
            flag = false;
        }
        if (password == null || password.trim().length() == 0) {
            passwordLoginHint.setText("* Password cannot be empty");
            flag = false;
        }
        
        if (username != null && username.trim().length() != 0) {
            int result = DataHandler.checkUsernameLogin(username);
            if (result == 0) {
                usernameLoginHint.setText("* The user does not exist");
                flag = false;
            } else {
                usernameLoginHint.setText(" ");
            }
        }
        if (flag) {
            int result = DataHandler.checkLogin(usernameLogin.getText(), passwordLogin.getText());
            if (result == 0) {
                passwordLoginHint.setText("* Wrong password");
            } else if (result == 1) {
                UserHome2 userHome = new UserHome2(usernameLogin.getText());
                userHome.setVisible(true);
                userHome.setResizable(false);
                userHome.setLocationRelativeTo(null);
                this.dispose();
            }

        }

    }//GEN-LAST:event_loginBTMouseReleased

    private void usernameLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameLoginFocusGained
        // TODO add your handling code here:
        usernameLoginHint.setText(" ");
    }//GEN-LAST:event_usernameLoginFocusGained

    private void passwordLoginFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginFocusGained
        // TODO add your handling code here:

        passwordLoginHint.setText(" ");

    }//GEN-LAST:event_passwordLoginFocusGained

    private void usernameSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameSignupFocusGained
        // TODO add your handling code here:

        usernameSignupHint.setText(" ");

    }//GEN-LAST:event_usernameSignupFocusGained

    private void passwordSignupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordSignupFocusGained
        // TODO add your handling code here:

        passwordSignupHint.setText(" ");
    }//GEN-LAST:event_passwordSignupFocusGained

    private void usernameSignupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameSignupFocusLost
        // TODO add your handling code here:
        String username = usernameSignup.getText();
        if (username != null && username.trim().length() != 0) {
            System.out.println("usernameSignupFocusLost");
        }
//        usernameLoginHint.setText(" ");
//        passwordLoginHint.setText(" ");
//        usernameSignupHint.setText(" ");
//        passwordSignupHint.setText(" ");
    }//GEN-LAST:event_usernameSignupFocusLost

    private void usernameLoginFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameLoginFocusLost
        // TODO add your handling code here:
        String username = usernameLogin.getText();

        if (username != null && username.trim().length() != 0) {
            int result = DataHandler.checkUsernameLogin(username);
            if (result == 0) {
                usernameLoginHint.setText("* The user does not exist");
            } else {
                usernameLoginHint.setText(" ");
            }
        }
    }//GEN-LAST:event_usernameLoginFocusLost

    private void signupBTMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBTMouseReleased
        // TODO add your handling code here:
        String username = usernameSignup.getText();
        String password = passwordSignup.getText();
        boolean flag = true;
        if (username == null || username.trim().length() == 0) {
            usernameSignupHint.setText("* Username cannot be empty");
            flag = false;
        }
        if (password == null || password.trim().length() == 0) {
            passwordSignupHint.setText("* Password cannot be empty");
            flag = false;
        }
        if (flag) {
            System.out.println();
        }
    }//GEN-LAST:event_signupBTMouseReleased

    private void signupBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBTMouseEntered
        // TODO add your handling code here:
        signupBT.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_signupBTMouseEntered

    private void signupBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupBTMouseExited
        // TODO add your handling code here:
        signupBT.setBackground(new Color(253, 207, 102));
    }//GEN-LAST:event_signupBTMouseExited

    private void loginBTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBTMouseEntered
        // TODO add your handling code here:
        loginBT.setBackground(new Color(255, 51, 51));
    }//GEN-LAST:event_loginBTMouseEntered

    private void loginBTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBTMouseExited
        // TODO add your handling code here:
        loginBT.setBackground(new Color(253, 207, 102));
    }//GEN-LAST:event_loginBTMouseExited

    private void backToLoginLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginLabelMouseEntered
        // TODO add your handling code here:
        backToLoginLabel.setForeground(new Color(255, 51, 51));
    }//GEN-LAST:event_backToLoginLabelMouseEntered

    private void backToLoginLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToLoginLabelMouseExited
        // TODO add your handling code here:
        backToLoginLabel.setForeground(new Color(253, 207, 102));
    }//GEN-LAST:event_backToLoginLabelMouseExited

    private void signupNowLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupNowLabelMouseEntered
        // TODO add your handling code here:
        signupNowLabel.setForeground(new Color(255, 51, 51));
    }//GEN-LAST:event_signupNowLabelMouseEntered

    private void signupNowLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupNowLabelMouseExited
        // TODO add your handling code here:
        signupNowLabel.setForeground(new Color(253, 207, 102));
    }//GEN-LAST:event_signupNowLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backToLoginLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel loginBT;
    private javax.swing.JPanel loginLogo;
    private javax.swing.JPanel loginPage;
    private javax.swing.JPasswordField passwordLogin;
    private javax.swing.JLabel passwordLoginHint;
    private javax.swing.JPasswordField passwordSignup;
    private javax.swing.JLabel passwordSignupHint;
    private javax.swing.JPanel signupBT;
    private javax.swing.JPanel signupLogo;
    private javax.swing.JLabel signupNowLabel;
    private javax.swing.JPanel signupPage;
    private component.PanelSlide slide;
    private javax.swing.JLabel underline1;
    private javax.swing.JLabel underline2;
    private javax.swing.JLabel underline3;
    private javax.swing.JLabel underline4;
    private javax.swing.JPanel userLogin;
    private javax.swing.JPanel userSignup;
    private javax.swing.JTextField usernameLogin;
    private javax.swing.JLabel usernameLoginHint;
    private javax.swing.JTextField usernameSignup;
    private javax.swing.JLabel usernameSignupHint;
    // End of variables declaration//GEN-END:variables
}
